Repository Maxwell-Baird/Dungeon-Crawler, pull requests merged in 2020-07, with the labels that each got.

#16 Feature/initialize
  .gitignore
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App/App.css
  src/App/App.js
  src/App/App.test.js
  src/UserStats/UserStats.css
  src/UserStats/UserStats.js
  src/index.css
  src/index.js
  src/playerState/index.js
  src/playerState/reducer.js
Labels: Front End, enhancement, good first issue

#20 Feature/map screen
  package-lock.json
  package.json
  src/Actions/Actions.css
  src/Actions/Actions.js
  src/Actions/Actions.test.js
  src/App/App.css
  src/App/App.js
  src/Description/Description.css
  src/Description/Description.js
  src/Description/Description.test.js
  src/Map/Map.css
  src/Map/Map.js
  src/Map/Map.test.js
  src/Map/MapImage.js
  src/UserStats/UserStats.css
  src/UserStats/UserStats.js
  src/index.css
  src/index.js
Labels: Chore, Front End, Phase 1, User Story, enhancement

#21 Encounters
  src/Actions/Actions.css
  src/Actions/Actions.js
  src/App/App.js
  src/Description/Description.css
  src/Encounters/Encounters.css
  src/Encounters/Encounters.js
  src/Encounters/Encounters.test.js
Labels: Front End, User Story, enhancement

#25 Feature/encounter be hookup
  src/Actions/Actions.css
  src/Actions/Actions.js
  src/App/App.js
  src/Description/Description.js
  src/Encounters/Encounters.css
  src/Encounters/Encounters.js
  src/encounterState/index.js
  src/encounterState/reducer.js
  src/index.js
Labels: Front End, Phase 1, Phase 2, User Story, enhancement

#37 Feature/dotenv
  .env.development
  .env.production
  package.json
  src/encounterState/index.js
Labels: Chore, Deployment, Front End, Phase 2

#38 Allow FE to use descriptions from BE
  src/Description/Description.js
Labels: Back End, Chore, Front End, Phase 3, enhancement

#40 Add coverage command
  package.json
Labels: Chore, Front End, Testing, documentation, enhancement

#45 Bugfix/lint
  src/App/App.test.js
  src/Description/Description.js
  src/Description/Description.test.js
  src/Encounters/Encounters.test.js
  src/Fight/FightActions/FightActions.test.js
  src/Login/Login.js
  src/Login/Login.test.js
  src/Map/Map.js
  src/TestWrapper/TestWrapper.js
  src/UserStats/UserStats.test.js
Labels: Front End, Testing, bug
